# Generated by Django 4.2.3 on 2023-07-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='is_actived',
            new_name='is_activated',
        ),
    ]
